defaults:
  - _self_
  - algo: ppg_lag
  - env: safety_car

# Global Runner Settings
seed: 222 #42, 69, 222
total_steps: 10000000
sps_logging_interval: 10
device: "cpu"

# WANDB (Global logging settings)
wandb:
  entity: "safe_rl_lab"
  project_name: "ppo_in_sg"
  group: null
  run_name: null